apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: ngovietduc20088/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync: 
        '**/*.js': '.'
        '**/*.css': '.'
        '**/*.html': '.'